title: System File Checker - Scan all Protected Files to Verify Their Versions
theme: jekyll-theme-cayman
google_analytics: UA-277487068-1
description: <a href="https://sites.google.com/view/systemfilecheckerr/"><img src="/black.png"alt="System File Checker"/></a>


